[tool.poetry]
name = "day-02"
version = "0.1.0"
description = ""
authors = ["julas23 <julianoas@msn.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
